shared_configs:
  simple_job_steps: &simple_job_steps
    - checkout
    - run:
        name: Run tests
        command: |
          make ci

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build-1-15:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.15
    steps: *simple_job_steps

  build-1-16:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.16
    steps: *simple_job_steps

  build-1-17:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.17
    steps: *simple_job_steps

  build-1-18:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.18
    steps: *simple_job_steps

  build-1-19:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19
    steps: *simple_job_steps

workflows:
  pr-build-test:
    jobs:
      - build-1-15
      - build-1-16
      - build-1-17
      - build-1-18
      - build-1-19
